lib: [
  "/Users/jared/clone/apps/isomagic-todos/server/_esy/default/store/b/isomagic_todos-bc3131e0/install/default/lib/isomagic-todos/META" {"META"}
  "/Users/jared/clone/apps/isomagic-todos/server/_esy/default/store/b/isomagic_todos-bc3131e0/install/default/lib/isomagic-todos/dune-package" {"dune-package"}
  "/Users/jared/clone/apps/isomagic-todos/server/_esy/default/store/b/isomagic_todos-bc3131e0/install/default/lib/isomagic-todos/opam" {"opam"}
]
bin: [
  "/Users/jared/clone/apps/isomagic-todos/server/_esy/default/store/b/isomagic_todos-bc3131e0/install/default/bin/server" {"server"}
]
